name: Build and Deploy
on:
  push:
    branches: [main]
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install and Build
        run: |
          npm install
          # We keep the base-href as the repo name so the URL works
          npx ng build --configuration production --base-href=/angular-hr-dashoard/

      - name: Deploy to GH Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # CHANGE THIS LINE specifically to match your internal project name
          folder: dist/hr-management-system/browser 
          branch: gh-pages